from   typing  import List
from  pydantic import BaseModel, Field

class Source(BaseModel):
    url:str=Field(description="The URL of the source")

class  AgentResponse(BaseModel):
    sources:List[Source]=Field(default_factory=list,description="List of sources used to generate answer")
    answer:str=Field(description="The final answer generated by the agent")